[workspace]
members = [
  "parity-base",
  "parity-root",
  "private-kernel-init",
  "private-kernel-inner",
  "private-kernel-reset",
  "rollup-tx-base-private",
  "rollup-tx-base-public",
  "rollup-tx-merge",
  "rollup-block-root",
  "rollup-block-merge",
  "rollup-checkpoint-root",
  "rollup-root",
]
